apiVersion: apps/v1
kind: Deployment
metadata:
  name: hab-watchdog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hab-watchdog
  template:
    metadata:
      labels:
        app: hab-watchdog
    spec:
      containers:
      - name: hab-watchdog
        image: oaasgaa01/hab-watchdog:0.1.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred